[gcp_service_account]
type = "service_account"
project_id = "teste-pai-482601"
private_key_id = "49416dfc2658982ff5d1c2bfaf1c071d740f99ce"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDNpTMz+T4+th5X
Y7x1KWEwYpH26J0VuqZPBu3wUFAFolRhf1BvsfW9ynQy8EYcMJ/sB0SW8B28CAHF
+HWwnOY7Hmr6g8bTfsQ5W1qsgY9NVeWHLXSZP3ttpR9vuJPfO+4Qp36MI0MYaJgn
4XY875njJRuuy/X0nlZ56m/3v4tRoEM+68DbQuqXLPpb7yxxTDQjzRyKCUciawZ3
tmjy4xgD9GtM1znZPPZmmfz3k3CEWMXMfB38ehRDfkX54VCN3IASr46dRijGSTtC
bvnf1AW2y26cZSVCIxzwg0p3w1sEnGj1Bw0V01AyaLX4031lnJIWeG1Hnbsp3m+3
jfDvtnWlAgMBAAECggEACI8P4W/UIFG2qQKQQ1i6tYP8uR0wUklAeJyKf2jsvlrX
gFMVkBwTD59jFJIZ0OdRZtR5DWLtw6l93y4sXnKPfrXYN6Zk81KVuq9kgKhH/UlH
FeSVencdh+ymza8NxkKrVSCrerbfcC09W/Byr2bne8doNZnsxJwTjE38uqp2IXFx
OWTx1hmG9ooCNYe1mMZ/FJDLZlRUbCISoHZHDrM4PV56ZYPa1km6rOCmw2083Ksk
WQNfxhcVGgNUn36Du0hIXE33jkfk2ca9ACrrcqDemciVDWTvGJGVIDl4EgdFCvZ7
jGJoVVVHAAmrA4UDsr8Xviamb0a2CedSjGip6amE1wKBgQD5gLW6K8tR9TyxiMNn
d45nabzZFOkfR/A2pBuFyq6rOT+1turqb87bwADBozCYUdMOkjYjmZISsoVXCncW
AQoGo4Sz3x3bjsSghwm/vSLtMEsvnM3rW/Ie0aWsl/9uAr5h6JcVm2NjaeWN529N
2CSLpqdPWaTDFiu9bHyKz641RwKBgQDTAB4vp3iUveZOrUAycszohIlESQ4F8v3z
J46QfmUhha5gEEFR+rzOE2876q3ewqboWJ6uPfOJmaZhWxBuEx9FViZ+LbF1WZg7
Cj25YfzyFnvEUliYMSOC7DTTx0S+3bxmevdaXlKMXqoh/yZIl7akofNhsHvbWLci
DDJL1K2jswKBgDFsU5M7VZ04jPtF8h8uyaCmi2gdAkjWATlxrJoGGi+EuaAPSd2C
pGFXWU8COoARxVMfl2XZ59uYTV1+jzRmpEvIXGMdEVcKotyBo2a92otNg7c8wnWa
0w1TzhOwUELEfF38quD21Os+cOB5Nc0fwa2AJ6hKQ575Z1SwhsMgfIvFAoGAKCKT
m1jttM1Sa5DE71Oq6mebfKOwySzpZUEW+yEvt2qoOpmc8y0QkNpdhDYlkIPSH8wL
kvUxx/C0FzytKWL1xciXVdT3Nm0uabyO9R5QcPQZ4sQPGhPuv06S1d3Hk861sYCe
YFAkv5KaJhFUhOZm1XYAx4o8ZQLBAvby8j2oMcUCgYBnBKuwiPOfDSN0u3a5bf0+
wi7FmNRrKwX/UHwwHPVoIaz6oWGHN/rgaWXJzo+MvoXXNU3VEk/cryK+L2av/eQG
elOCTCChO0brCi3cNBzdbELz77LZpQ+IsauMf3rWIL8cECY05BKGR9ROFkpZJCc4
deDatQm1ELI/Ev8YALC9Eg==
-----END PRIVATE KEY-----"""
client_email = "conta-teste-controle-pai@teste-pai-482601.iam.gserviceaccount.com"
client_id = "109697063289965246713"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/conta-teste-controle-pai%40teste-pai-482601.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
